name: Linux Continue Local LLM Config
version: 0.0.1
schema: v1
models:
  - name: CodeStral
    provider: ollama
    model: codestral:latest
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
      - apply
      - rerank
      - autocomplete
